// <auto-generated />
using System;
using Kodx.Rpi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kodx.Rpi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KodxRpiDbContext))]
    [Migration("20260716213445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kodx.Rpi.Domain.Rpis.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<int>("RpiEditionId")
                        .HasColumnType("integer")
                        .HasColumnName("rpi_edition_id");

                    b.HasKey("Id")
                        .HasName("pk_publications");

                    b.HasIndex("Numero")
                        .HasDatabaseName("ix_publications_numero");

                    b.HasIndex("RpiEditionId")
                        .HasDatabaseName("ix_publications_rpi_edition_id");

                    b.ToTable("publications", (string)null);
                });

            modelBuilder.Entity("Kodx.Rpi.Domain.Rpis.RpiEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao");

                    b.Property<int>("Edicao")
                        .HasColumnType("integer")
                        .HasColumnName("edicao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_rpi_editions");

                    b.HasIndex("Edicao", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_rpi_editions_edicao_tipo");

                    b.ToTable("rpi_editions", (string)null);
                });

            modelBuilder.Entity("Kodx.Rpi.Domain.Rpis.RpiProcessingAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("RpiEditionId")
                        .HasColumnType("integer")
                        .HasColumnName("rpi_edition_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_rpi_processing_attempts");

                    b.HasIndex("RpiEditionId", "Stage")
                        .HasDatabaseName("ix_rpi_processing_attempts_rpi_edition_id_stage");

                    b.ToTable("rpi_processing_attempts", (string)null);
                });

            modelBuilder.Entity("Kodx.Rpi.Domain.Rpis.Publication", b =>
                {
                    b.HasOne("Kodx.Rpi.Domain.Rpis.RpiEdition", null)
                        .WithMany()
                        .HasForeignKey("RpiEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publications_rpi_editions_rpi_edition_id");

                    b.OwnsOne("Kodx.Rpi.Domain.Rpis.PublicationPayload", "Payload", b1 =>
                        {
                            b1.Property<int>("PublicationId");

                            b1.Property<string>("Cabecalho1");

                            b1.Property<string>("Cabecalho2");

                            b1.Property<string>("Cabecalho3");

                            b1.Property<string>("Conteudo");

                            b1.Property<int>("IndexFim");

                            b1.Property<int>("IndexInicio");

                            b1.Property<string>("Orgao");

                            b1.Property<int>("Pagina");

                            b1.Property<string>("Rodape");

                            b1.PrimitiveCollection<string>("TodosNumeros")
                                .IsRequired();

                            b1.HasKey("PublicationId");

                            b1.ToTable("publications");

                            b1
                                .ToJson("payload")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PublicationId")
                                .HasConstraintName("fk_publications_publications_id");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("Kodx.Rpi.Domain.Rpis.RpiProcessingAttempt", b =>
                {
                    b.HasOne("Kodx.Rpi.Domain.Rpis.RpiEdition", null)
                        .WithMany()
                        .HasForeignKey("RpiEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rpi_processing_attempts_rpi_editions_rpi_edition_id");
                });
#pragma warning restore 612, 618
        }
    }
}
