namespace Kodx.Rpi.Infrastructure.Rpis.PublicationExtraction;

/// <summary>Porta de RegrasDeNegocio/Leitura/RpiMarcas.cs do legado.</summary>
internal static class RpiMarcasRules
{
    public static PublicationTypeRules Create() => new(
        SearchTerms:
        [
            new(@"[\r\n][\d]{8,13}", IsRegex: true, PublicationFieldType.Publicacao, BreaksContinuity: true),
            new("\r\nC O M U N I C A D O\r\n", IsRegex: false, PublicationFieldType.Publicacao, BreaksContinuity: true),
            new("\r\nLEIA COM ATENÇÃO\r\n", IsRegex: false, PublicationFieldType.Publicacao, BreaksContinuity: true),
            new(@"MARCAS - RPI [\d]{3,} de [\d]{1,2}[/][\d]{1,2}[/][\d]{2,4} [\d]{1,}[\r\n]", IsRegex: true, PublicationFieldType.Pagina, BreaksContinuity: false),

            new("\r\nPedidos de registro de marca\r\nem andamento\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nPedidos de registro de marca em andamento\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nDesistências em pedido de registro de marca\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nConcessões de registros de marca\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nRegistros de marca extintos\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nRegistros de marca cancelados de ofício\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCaducidades de registros de marca\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nProrrogações de registros de marca\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nAnotações de alteração de nome e endereço\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nAnotações de transferência de titularidade\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nRecursos\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nOutras petições\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nAnulação de despachos\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nNotificações e decisões judiciais\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nDisponibilidade de documentos oficiais\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nPedidos de registro de marca considerados inexistentes\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nPedidos de registro de marca definitivamente arquivados\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nPedidos de registro de marca arquivados de ofício\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nNulidades administrativas de registros de marca\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nAnotações de limitação ou ônus\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nRenúncias ao registro de marca\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nRespostas da Comissão de Classificação de Produtos e Serviços\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nPedidos de registro de marca considerados\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nPedidos de registro de marca definitivamente\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nMarcas de alto renome\r\n", false, PublicationFieldType.Cabecalho1, true),

            new("\r\nExame de mérito: Deferimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPublicação de pedido para oposição\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nRegistro de marca concedido\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nRegistro de marca prorrogado\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExame de mérito: Indeferimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nNotificação de oposição para manifestação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExame de mérito: Sobrestamento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPelo fim da vigência\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nNotificação de recurso para manifestação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExame de mérito: Exigência\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nOutros despachos\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nDisponibilidade de outros documentos oficiais\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExame de mérito: petição de retificação (366) atendida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nNotificação de procedimento judicial\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nDecisão da nulidade: Negado provimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPor falta de resposta à exigência de mérito\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nRepublicação de pedido para oposição\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nDecisão do recurso: Provimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nEm vista da falta de pagamento da retribuição\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nNotificação de decisão judicial\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExame de mérito: petição de retificação (366) não atendida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nDecisão do recurso: Negado provimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExigência formal\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nNotificação de caducidade para manifestação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPela caducidade\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nAnulação de despachos relativos a petições\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPor falta de procuração\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPor falta de documentos relativos a marca coletiva\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPor falta de pagamento das retribuições relativas à concessão do registro\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExigência de pagamento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nDecisão da nulidade: Provimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nInstrução técnica: Sobrestamento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nEm vista da ausência de resposta a exigência formal\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPor falta de documentos relativos a marca de certificação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nInstrução técnica: Exigência de mérito\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExigência de conformidade de petição\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExame de mérito: Deferimento parcial\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nRegistros de marca cancelados de ofício\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nEm vista da ausência de resposta a exigência de pagamento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPedidos de registro de marca arquivados de ofício\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nInstrução técnica: Ciência de parecer\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nAnulação de despachos relativos a processos de registro de marca\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nRespostas da Comissão de Classificação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nDecisão da nulidade: Provimento parcial\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nDecisão do recurso: Provimento parcial\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nNotificação de nulidade administrativa, por requerimento de terceiros, para manifestação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nPela inobservância do artigo 217 da Lei da Propriedade Industrial\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nInstruções para os pagamentos e comprovação das retribuições LEIA COM ATENÇÃO\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nExigência sobre alto renome\r\n", false, PublicationFieldType.Cabecalho2, true)
        ],
        SyntheticField: PublicationFieldType.Cabecalho3,
        SyntheticReferenceField: PublicationFieldType.Cabecalho2,
        ProcessNumberPatterns: [@"[\d]{8,13}"]);
}
