namespace Kodx.Rpi.Infrastructure.Rpis.PublicationExtraction;

/// <summary>Porta de RegrasDeNegocio/Leitura/RpiPatentes.cs do legado.</summary>
internal static class RpiPatentesRules
{
    public static PublicationTypeRules Create() => new(
        SearchTerms:
        [
            new(@"[\r\n][(][\d]{2}[)] BR [\d]{2} [\d]{4} [\d-]{6,8}", IsRegex: true, PublicationFieldType.Publicacao, BreaksContinuity: true),
            new(@"[\r\n][(][\d]{2}[)] PI [\d-]{7,9}", IsRegex: true, PublicationFieldType.Publicacao, BreaksContinuity: true),
            new(@"[\r\n][(][\d]{2}[)] MU [\d-]{7,9}", IsRegex: true, PublicationFieldType.Publicacao, BreaksContinuity: true),
            new(@"[\r\n][(][\d]{2}[)] C[0-9] [\d-]{7,9}", IsRegex: true, PublicationFieldType.Publicacao, BreaksContinuity: true),
            new(@"PATENTES - RPI [\d]{3,} de [\d]{1,2}[/][\d]{1,2}[/][\d]{2,4} [\d]{1,}[\r\n]", IsRegex: true, PublicationFieldType.Pagina, BreaksContinuity: false),
            new(@"Patentes – RPI [\d]{3,} de [\d]{1,2} de [A-zçã]{4,12} de [\d]{2,4} [\d]{1,}[/][\d]{1,}[\r\n]", IsRegex: true, PublicationFieldType.Pagina, BreaksContinuity: false),

            new("\r\nCódigo Presidência - Recurso\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Presidência - Nulidade\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Pedido Internacional PCT/BR Designado ou Eleito\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Depósito\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Publicação do Pedido\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Exigências Técnicas e Formais\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Ciência de Parecer\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Anuidade do Pedido\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Decisão\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Arquivamento\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Recurso\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Outros Referentes a Pedidos\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Concessão de Patente e Certificado de Adição de Invenção\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Extinção de Patente e Certificado de Adição de Invenção\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Outros Referentes a Patentes/Certificados de Adição de Invenção\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Anuidade de Patente\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Anotação de Alteração de nome e/ou sede, de Transferência e de\r\nLimitação ou Ônus de Pedido, Patente e Certificado de Adição de Invenção\r\n", false, PublicationFieldType.Cabecalho1, true),
            new("\r\nCódigo Patentes Verdes\r\n", false, PublicationFieldType.Cabecalho1, true),

            new("\r\nCódigo 100 - Recurso conhecido e provido. Reformada a Decisão recorrida e\r\ndeferido o pedido\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 104 - Recurso conhecido e provido. Reformada a Decisão recorrida.\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 111 - Recurso conhecido e negado provimento. Mantido o\r\nindeferimento do pedido\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 120 - Tome Conhecimento do Parecer Técnico\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 121 - Exigência\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 135 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 136 - Petição não Conhecida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 205 - Intimação para manifestação por parte do titular e do requerente\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.1 - Publicação Internacional – PCT. Apresentação de petição de\r\nrequerimento de entrada na fase nacional\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.2 - Notificação – Pedido Retirado – PCT\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.2.1 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.2.3 - Decisão Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.3 - Notificação - Fase Nacional - PCT\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.3.1 - Retificação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.4 - Restabelecimento de Direito para Entrada na Fase Nacional do\r\nPCT concedido\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.4.1 - Restabelecimento de Direito para Entrada na Fase Nacional do\r\nPCT negado\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 1.5 - Exigências Diversas\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 2.1 - Pedido de Patente ou Certificado de Adição de Invenção\r\ndepositado\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 2.4 - Notificação de Depósito do Pedido Dividido - Art 26 inciso I da\r\nLPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 2.5 - Exigência - Art. 21 da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 2.6 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 2.7 - Republicação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 2.10 - Requerimento de Pedido de Patente ou Certificado de Adição\r\nde Invenção\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 3.1 - Publicação do Pedido de Patente ou de Certificado de Adição de\r\nInvenção\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 3.2 - Publicação Antecipada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 3.7 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 6.1 - Exigência Técnica\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 6.6 - Exigência Formal\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 6.7 - Outras Exigências\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 6.8 - Exigência Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 6.9 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 7.1 - Conhecimento de Parecer Técnico\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 7.3 - Republicação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 7.4 - Ciência relacionada com o Art. 229-C da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 8.6 - Arquivamento - Art. 86 da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 8.7 - Restauração\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 8.8 - Despacho Anulado\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 8.11 - Manutenção do Arquivamento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 9.1 - Deferimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 9.1.3 - Republicação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 9.2 - Indeferimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.1 - Arquivamento - Art. 33 da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.2 - Arquivamento - Art. 36 §1° da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.4 - Arquivamento - Art. 38 § 2° da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.5 - Arquivamento - Art. 34 da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.6.1 - Arquivamento da Petição – Art. 216 §2º da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.11 - Arquivamento - Art. 17 § 2º da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.13 - Despacho Anulado\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.14 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 11.17 - Arquivamento do pedido de Certificado de Adição de Invenção\r\n– Art. 77 da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 12.2 - Recurso Contra o Indeferimento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 12.3 - Recurso Contra o Arquivamento\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 12.6 - Outros Recursos\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.7 - Petição não Conhecida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.9 - Perda de Prioridade\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.11 - Alteração de Classificação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.12 - Renumeração\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.21 - Numeração Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.24 - Notificação de requerimento de exame prioritário de pedido de\r\npatente\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.30 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 15.31 - Despacho Anulado\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 16.1 - Concessão de Patente ou Certificado de Adição de Invenção\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 16.3 - Retificação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 16.4 - Concessão Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 21.6 - Extinção da patente para fins da restauração nos termos do art.\r\n87 da LPI.\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 21.8 - Despacho Anulado\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 22.15 - Patente “SUB JUDICE”\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 24.2 - Exigência de Complementação da Retribuição Anual\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 24.4 - Restauração\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 24.10 - Manutenção da Extinção - Art. 78 inciso IV da LPI\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.1 - Transferência Deferida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.2 - Transferência Indeferida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.3 - Transferência em Exigência\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.4 - Alteração de Nome Deferida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.5 - Alteração de Nome Indeferida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.7 - Alteração de Sede Deferida\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.11 - Republicação\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 25.12 - Publicação Anulada\r\n", false, PublicationFieldType.Cabecalho2, true),
            new("\r\nCódigo 27.1 - Notificação de Solicitação para Participação no Programa de\r\nPatentes Verdes\r\n", false, PublicationFieldType.Cabecalho2, true)
        ],
        SyntheticField: PublicationFieldType.Cabecalho3,
        SyntheticReferenceField: PublicationFieldType.Cabecalho2,
        ProcessNumberPatterns:
        [
            @"BR [\d]{2} [\d]{4} [\d-]{6,8}",
            @"PI [\d-]{7,9}",
            @"MU [\d-]{7,9}",
            @"C[0-9] [\d-]{7,9}"
        ]);
}
